{% set version = "2.13.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-labelled
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/labelled_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/labelled/labelled_{{ version }}.tar.gz
  sha256: 9e2e82a42343b62f8a476d4dd7b13e9ffb3ee2c4e23bdf2cd29ef25b3dffa237

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-haven >=2.3.1
    - r-lifecycle
    - r-rlang
    - r-stringr
    - r-tidyr
    - r-vctrs
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-haven >=2.3.1
    - r-lifecycle
    - r-rlang
    - r-stringr
    - r-tidyr
    - r-vctrs

test:
  commands:
    - $R -e "library('labelled')"           # [not win]
    - "\"%R%\" -e \"library('labelled')\""  # [win]

about:
  home: https://github.com/larmarange/labelled
  license: GPL-3.0-only
  summary: Work with labelled data imported from 'SPSS' or 'Stata' with 'haven' or 'foreign'. This package provides useful functions to deal with "haven_labelled" and "haven_labelled_spss" classes introduced by 'haven' package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: labelled
# Type: Package
# Title: Manipulating Labelled Data
# Version: 2.1.0
# Maintainer: Joseph Larmarange <joseph@larmarange.net>
# Authors@R: c( person("Joseph", "Larmarange", email = "joseph@larmarange.net", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-7097-700X")), person("Daniel", "Ludecke", role = "ctb"), person("Hadley", "Wickham", role = "ctb"), person("Bojanowski", "Michal", role = "ctb") )
# Description: Work with labelled data imported from 'SPSS' or 'Stata' with 'haven' or 'foreign'. This package provides useful functions to deal with "haven_labelled" and "haven_labelled_spss" classes introduced by 'haven' package.
# License: GPL-3
# Encoding: UTF-8
# Imports: haven (>= 2.1.0), dplyr, stats
# Suggests: testthat, knitr, rmarkdown, questionr, snakecase
# Enhances: memisc
# LazyData: true
# URL: https://github.com/larmarange/labelled
# BugReports: https://github.com/larmarange/labelled/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-02-22 18:55:46 UTC; jlarmarange
# Author: Joseph Larmarange [aut, cre] (<https://orcid.org/0000-0001-7097-700X>), Daniel Ludecke [ctb], Hadley Wickham [ctb], Bojanowski Michal [ctb]
# Repository: CRAN
# Date/Publication: 2019-02-25 12:50:07 UTC
