{% set version = "2.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-labelled
  version: {{ version|replace("-", "_") }}

source:
  fn: labelled_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/labelled_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/labelled/labelled_{{ version }}.tar.gz
  sha256: 0d292ad898bf9c53b2bd7b133469f9102756f4d6e69f827eb7d78e1c154aea3b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-haven >=1.0.0
  run:
    - r-base
    - r-dplyr
    - r-haven >=1.0.0

test:
  commands:
    - $R -e "library('labelled')"           # [not win]
    - "\"%R%\" -e \"library('labelled')\""  # [win]

about:
  home: https://github.com/larmarange/labelled
  license: GPL-3
  summary: Work with labelled data imported from 'SPSS' or 'Stata' with 'haven' or 'foreign'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
