appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WRQ/G6y9Pu71u5HhimgROuzR9t8f6nqjkSAOOmKWMqTdY55LYH6g1AnhVEYZReyCqu3fhB5p6OONExZdpJ7JCTLj5HjhPK1arxvfU0CKZXWwxADPx9GY0Kb6Sus/fUVW9S0MZBOXSN+cnmn1hhOb7mLj2pu9ee6fHWv7b+n8Dwb7i6RumkRfKrhLjqLp7vZEJz7Ixg0rE85RsOGr7FosoTJ5sMSQ6YIQbh7nz3mAfcB7sGz4aQXUS5ShcSsjk1Vx8DA3Ow5gE/rK77j1xaWPmoQqkmDlYYOv3RRpI0aa9JA8fIZEWgovEwq2ObA/Hqyjj6kItPBsHr7YYtsN5Xmd2w2HNW/gtWIfnWxCgvTgB/ZdGWL7AUm2Gurx/9R4Qv2ZLyrF/+girGdJ8WU0HDyjiqv6YTS8OUTlYQ9BFZmxChIg2dgMec/A1JbHvb1yRZVp/Td6SIzFG9HhXC9otrrLGacxW2qGOKevRQRoNUqvc6C9PvfiHdHlJzKf/fQ5J6wZEpQJ4qMP3PY1mlSaIk6TafWNzM05CQEfLKWBqesjX65WmGkiv1W7RF8cU1SdSmA5pMkD3D7YA2mcEOzRcUBcOLd2u9x9bc/MTmOnPxVMXol0H2jkfQ/Xa3s7txRff0zJvoT+/OCsxhy+wlqIo2BcbKhdRDdzKmBJ/hOhnzv3UYs=}
bot:
  automerge: true
